version: "3.9"  # optional since v1.27.0
services:
  influx:
    image: influxdb
    ports: ["8086:8086"]
    volumes:
      - /var/data/influxdb:/var/lib/influxdb2
    networks:
      - shared
    restart: always
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: team-kiss
      DOCKER_INFLUXDB_INIT_PASSWORD: password
      DOCKER_INFLUXDB_INIT_ORG: team-kiss
      DOCKER_INFLUXDB_INIT_BUCKET: sensordata
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: a2ZPCjFHSBbD1YBS8lkTRTjvEQc2pgxBybqWcZ_8J89a94OzZPYOLzzi-scvMzFnci1hSTn6eJBoiI7CNanQCA==
  registry:
    image: registry
    ports: ["8087:5000"]
    volumes:
      - /var/data/registry:/var/lib/registry
    networks:
      - shared
    restart: always

networks:
  shared:
    name: shared-services-net
